spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/dxworks
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

web3:
  client-address: http://127.0.0.1:8545 # Ganache / Besu / Infura RPC 주소
  private-key: ${PRIVATE_KEY}
  contract:
    address: ${CONTRACT_ADDRESS}
    transactionAddress: ${TRANSACTION_CONTRACT_ADDRESS}
  gas:
    price: 20000000000       # 20 Gwei
    limit: 6721975

# openAI
openai:
  model: ${OPENAI_MODEL}
  secret-key: ${OPENAI_SECRET_KEY}

secret-key: ${SECRET_KEY:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d}

gemini:
  api-key : ${KEY}

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  client_secret: ${KAKAO_SECRET_KEY}

aws:
  s3:
    bucket: ${S3_BUCKET_NAME}
  dynamodb:
    endpoint: https://dynamodb.ap-northeast-2.amazonaws.com
  credentials:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
  region:
    static: ap-northeast-2

